# Generated by Django 6.0.1 on 2026-02-26 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('city', models.CharField(max_length=100)),
                ('year_built', models.IntegerField()),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_unesco_heritage', models.BooleanField(default=False)),
                ('style', models.CharField(choices=[('GO', 'Gothic'), ('RO', 'Romanesque'), ('BA', 'Baroque'), ('NE', 'Neoclassical'), ('MO', 'Modern'), ('OT', 'Other')], default='OT', max_length=20)),
            ],
        ),
    ]
